url: "http://www.datascienceafrica.org" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/dsablog" # the subpath of your site, e.g. /blog
title: "Data Science Africa Blog" # the name of your site, e.g. ACME Corp.
collections:
  events:
    output: true
future: true
# title:              Data Science Africa
email:              info@datascienceafrica.org
description:        Home for everything DSA
author:             Data Science Africa
#baseurl:            "/startbootstrap-clean-blog-jekyll"
#url:                "https://startbootstrap.github.io"

# Social Profiles
twitter_username:   dsa_org
github_username:    datsciafrica
facebook_username:  DataScienceAfrica
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
